global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 22
  download_limit: 5
  last_check_time: '2025-12-24 13:23:39'
- name: 电锯人
  path: dianjuren
  last_chapter: 21
  download_limit: 5
  last_check_time: '2025-12-24 13:23:51'
