global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 37
  download_limit: 5
  last_check_time: '2025-12-26 03:13:39'
- name: 电锯人
  path: dianjuren
  last_chapter: 36
  download_limit: 5
  last_check_time: '2025-12-26 03:13:51'
