global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 49
  download_limit: 5
  last_check_time: '2026-02-11 04:14:01'
- name: 电锯人
  path: dianjuren
  last_chapter: 49
  download_limit: 5
  last_check_time: '2026-02-11 04:14:05'
