global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 32
  download_limit: 5
  last_check_time: '2025-12-25 03:15:30'
- name: 电锯人
  path: dianjuren
  last_chapter: 31
  download_limit: 5
  last_check_time: '2025-12-25 03:15:40'
