global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 49
  download_limit: 5
  last_check_time: '2026-01-29 03:52:52'
- name: 电锯人
  path: dianjuren
  last_chapter: 49
  download_limit: 5
  last_check_time: '2026-01-29 03:52:57'
