global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 373
  last_check_time: '2025-12-11 05:49:12'
  
- name: 电锯人
  path: dianjuren
  last_chapter: 240
  last_check_time: '2025-12-11 05:49:12'
