global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 27
  download_limit: 5
  last_check_time: '2025-12-24 14:58:28'
- name: 电锯人
  path: dianjuren
  last_chapter: 26
  download_limit: 5
  last_check_time: '2025-12-24 14:58:40'
