global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 366
  last_check_time: '2025-12-12 14:26:10'
- name: 电锯人
  path: dianjuren
  last_chapter: 245
  last_check_time: '2025-12-12 14:26:15'
