global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 373
  last_check_time: '2025-12-14 04:44:33'
- name: 电锯人
  path: dianjuren
  last_chapter: 248
  last_check_time: '2025-12-14 04:45:19'
