global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 365
  last_check_time: '2025-12-11 15:10:26'
- name: 电锯人
  path: dianjuren
  last_chapter: 247
  last_check_time: '2025-12-11 15:10:32'
