global:
  pdf_switch: 0
  pdf_password: None
comics:
- name: 海贼王
  path: haizeiwang
  last_chapter: 42
  download_limit: 5
  last_check_time: '2025-12-27 03:11:09'
- name: 电锯人
  path: dianjuren
  last_chapter: 41
  download_limit: 5
  last_check_time: '2025-12-27 03:11:22'
